openapi: 3.0.1
info:
  title: Star Wars
  description: ''
  version: '1.0'
servers:
  - url: https://demo-cmh-apim-dev-apim.azure-api.net/starwars
paths:
  /people:
    get:
      summary: Get People
      description: Get People
      operationId: get-people
      responses:
        '200':
          description: ''
  '/people/{id}':
    get:
      summary: Get Person By Id
      description: Get Person By Id
      operationId: get-person-by-id
      parameters:
        - name: id
          in: path
          description: ID of person to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People'
              example:
                count: 82
                next: https://swapi.dev/api/people/?page=2
                previous: ''
                results:
                  - name: Luke Skywalker
                    height: '172'
                    mass: '77'
                    hair_color: blond
                    skin_color: fair
                    eye_color: blue
                    birth_year: 19BBY
                    gender: male
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/6/
                    species: [ ]
                    vehicles:
                      - https://swapi.dev/api/vehicles/14/
                      - https://swapi.dev/api/vehicles/30/
                    starships:
                      - https://swapi.dev/api/starships/12/
                      - https://swapi.dev/api/starships/22/
                    created: '2014-12-09T01:50:51.0000000+00:00'
                    edited: '2014-12-20T09:17:56.0000000+00:00'
                    url: https://swapi.dev/api/people/1/
                  - name: C-3PO
                    height: '167'
                    mass: '75'
                    hair_color: n/a
                    skin_color: gold
                    eye_color: yellow
                    birth_year: 112BBY
                    gender: n/a
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/4/
                      - https://swapi.dev/api/films/5/
                      - https://swapi.dev/api/films/6/
                    species:
                      - https://swapi.dev/api/species/2/
                    vehicles: [ ]
                    starships: [ ]
                    created: '2014-12-10T03:10:51.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/2/
                  - name: R2-D2
                    height: '96'
                    mass: '32'
                    hair_color: n/a
                    skin_color: 'white, blue'
                    eye_color: red
                    birth_year: 33BBY
                    gender: n/a
                    homeworld: https://swapi.dev/api/planets/8/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/4/
                      - https://swapi.dev/api/films/5/
                      - https://swapi.dev/api/films/6/
                    species:
                      - https://swapi.dev/api/species/2/
                    vehicles: [ ]
                    starships: [ ]
                    created: '2014-12-10T03:11:50.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/3/
                  - name: Darth Vader
                    height: '202'
                    mass: '136'
                    hair_color: none
                    skin_color: white
                    eye_color: yellow
                    birth_year: 41.9BBY
                    gender: male
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/6/
                    species: [ ]
                    vehicles: [ ]
                    starships:
                      - https://swapi.dev/api/starships/13/
                    created: '2014-12-10T03:18:20.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/4/
                  - name: Leia Organa
                    height: '150'
                    mass: '49'
                    hair_color: brown
                    skin_color: light
                    eye_color: brown
                    birth_year: 19BBY
                    gender: female
                    homeworld: https://swapi.dev/api/planets/2/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/6/
                    species: [ ]
                    vehicles:
                      - https://swapi.dev/api/vehicles/30/
                    starships: [ ]
                    created: '2014-12-10T03:20:09.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/5/
                  - name: Owen Lars
                    height: '178'
                    mass: '120'
                    hair_color: 'brown, grey'
                    skin_color: light
                    eye_color: blue
                    birth_year: 52BBY
                    gender: male
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/5/
                      - https://swapi.dev/api/films/6/
                    species: [ ]
                    vehicles: [ ]
                    starships: [ ]
                    created: '2014-12-10T03:52:14.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/6/
                  - name: Beru Whitesun lars
                    height: '165'
                    mass: '75'
                    hair_color: brown
                    skin_color: light
                    eye_color: blue
                    birth_year: 47BBY
                    gender: female
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/5/
                      - https://swapi.dev/api/films/6/
                    species: [ ]
                    vehicles: [ ]
                    starships: [ ]
                    created: '2014-12-10T03:53:41.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/7/
                  - name: R5-D4
                    height: '97'
                    mass: '32'
                    hair_color: n/a
                    skin_color: 'white, red'
                    eye_color: red
                    birth_year: unknown
                    gender: n/a
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                    species:
                      - https://swapi.dev/api/species/2/
                    vehicles: [ ]
                    starships: [ ]
                    created: '2014-12-10T03:57:50.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/8/
                  - name: Biggs Darklighter
                    height: '183'
                    mass: '84'
                    hair_color: black
                    skin_color: light
                    eye_color: brown
                    birth_year: 24BBY
                    gender: male
                    homeworld: https://swapi.dev/api/planets/1/
                    films:
                      - https://swapi.dev/api/films/1/
                    species: [ ]
                    vehicles: [ ]
                    starships:
                      - https://swapi.dev/api/starships/12/
                    created: '2014-12-10T03:59:50.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/9/
                  - name: Obi-Wan Kenobi
                    height: '182'
                    mass: '77'
                    hair_color: 'auburn, white'
                    skin_color: fair
                    eye_color: blue-gray
                    birth_year: 57BBY
                    gender: male
                    homeworld: https://swapi.dev/api/planets/20/
                    films:
                      - https://swapi.dev/api/films/1/
                      - https://swapi.dev/api/films/2/
                      - https://swapi.dev/api/films/3/
                      - https://swapi.dev/api/films/4/
                      - https://swapi.dev/api/films/5/
                      - https://swapi.dev/api/films/6/
                    species: [ ]
                    vehicles:
                      - https://swapi.dev/api/vehicles/38/
                    starships:
                      - https://swapi.dev/api/starships/48/
                      - https://swapi.dev/api/starships/59/
                      - https://swapi.dev/api/starships/64/
                      - https://swapi.dev/api/starships/65/
                      - https://swapi.dev/api/starships/74/
                    created: '2014-12-10T04:16:29.0000000+00:00'
                    edited: '2014-12-20T09:17:50.0000000+00:00'
                    url: https://swapi.dev/api/people/10/
components:
  schemas:
    People:
      type: object
      properties:
        count:
          type: integer
        next:
          type: string
        previous: { }
        results:
          type: array
          items:
            required:
              - name
              - height
              - mass
              - hair_color
              - skin_color
              - eye_color
              - birth_year
              - gender
              - homeworld
              - films
              - species
              - vehicles
              - starships
              - created
              - edited
              - url
            type: object
            properties:
              name:
                type: string
              height:
                type: string
              mass:
                type: string
              hair_color:
                type: string
              skin_color:
                type: string
              eye_color:
                type: string
              birth_year:
                type: string
              gender:
                type: string
              homeworld:
                type: string
              films:
                type: array
                items:
                  type: string
              species:
                type: array
              vehicles:
                type: array
                items:
                  type: string
              starships:
                type: array
                items:
                  type: string
              created:
                type: string
              edited:
                type: string
              url:
                type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]