name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  functionPublishPath: "${{ github.workspace }}/functionapp"
  mainBicepPath: "${{ github.workspace }}/.infrastructure/bicep/main.bicep"
  functionSolutionPath: "${{ github.workspace }}/function-app/FunctionsOrderFulfillmentDemo.sln"
  bicepParametersPath: "${{ github.workspace }}/.infrastructure/bicep/parameters/main.dev.bicepparam"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.x"

      - name: Build Infrastructure Templates
        run: bicep build ${{ env.mainBicepPath }}

      - name: Restore and Build Function App
        run: |
          dotnet restore
          dotnet build ${{ env.functionSolutionPath }} --configuration Release

      - name: Publish Function App
        run: dotnet publish '**/*.csproj' --configuration Release --output ${{ env.functionPublishPath }}

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
          template: ${{ env.mainBicepPath }}
          parameters: ${{ env.bicepParametersPath }}

      - name: Deploy Function App
        uses: azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTION_APP_NAME }}
          package: ${{ env.functionPublishPath }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}